nurse:
	gcc encrypt.c patient.c auth.c nurse.c -lm -o nurse 2> build-log.txt
	./nurse

.PHONY: nurse

consultant:
	gcc encrypt.c patient.c auth.c consultant.c -lm -o consultant 2> build-log.txt
	./consultant

.PHONY: consultant